/*
  This class has been generated by the Code Generator
*/

package com.opentext.apps.gc.notifications;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;


public class NotificationInstanceDetails extends NotificationInstanceDetailsBase
{
    public NotificationInstanceDetails()
    {
        this((BusObjectConfig)null);
    }

    public NotificationInstanceDetails(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.opentext.apps.gc.notifications.NotificationInstanceDetails> getNotificationInstanceDetailsObjects(com.cordys.cpc.bsf.query.Cursor cursor)
    {
        // TODO implement body
        return null;
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
