/*
  This class has been generated by the Code Generator
*/

package com.opentext.apps.gc.notifications;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;


public abstract class NotificationInstanceDetailsBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_EmailIds = "EmailIds";
    public final static String ATTR_UserIds = "UserIds";
    public final static String ATTR_RoleIds = "RoleIds";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(NotificationInstanceDetails.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EmailIds);
                ai.setJavaName(ATTR_EmailIds);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UserIds);
                ai.setJavaName(ATTR_UserIds);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RoleIds);
                ai.setJavaName(ATTR_RoleIds);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public NotificationInstanceDetailsBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getEmailIds()
    {
        return getStringProperty(ATTR_EmailIds);
    }

    public void setEmailIds(String value)
    {
        setProperty(ATTR_EmailIds, value, 0);
    }

    public String getUserIds()
    {
        return getStringProperty(ATTR_UserIds);
    }

    public void setUserIds(String value)
    {
        setProperty(ATTR_UserIds, value, 0);
    }

    public String getRoleIds()
    {
        return getStringProperty(ATTR_RoleIds);
    }

    public void setRoleIds(String value)
    {
        setProperty(ATTR_RoleIds, value, 0);
    }


}
